### ISSUE TITLE
Tabs in admin

### ISSUE THREAD

**Issue by khalilr2k** [wpify/custom-fields#2]
Hi, is there way I organize the fields by tabs?
The tabs allow to group multiple fields under different tab panels.

**Comment by vaclavgreif** [comment]
Hi @khalilr2k , that's not currently possible, but we are working on a new version which will be a complete rewrite of the React code and we'll also include the tabs, as these are on the roadmap for quite some time already.

**Comment by khalilr2k** [comment]
Thanks,
is there way i can append a classes to field container in admin?

**Comment by mejta** [comment]
Hey @khalilr2k, 
Thank you for using the library. At the moment, it's not possible. But I'm adding that to the requirements for the next version.
Dan

**Comment by mejta** [comment]
Hey, @khalilr2k, please check the new version 4.0. It has been completely rewritten but is backwards compatible. Tabs support has also been added.

Documentation (in progress) is here:
https://github.com/wpify/custom-fields/blob/master/docs/index.md
