### ISSUE TITLE
Getting error message for some of the custom fields, while trying to click on view after edit/update the component

### ISSUE THREAD

**Issue by flurdy-AB14** [wpify/custom-fields#3]
Hi, there

We are using wpify/custom-fields at our end, recently we updated with the latest version, however we are facing some of the issues with this latest version. Whenever we are trying to view the content changes after edit/update the component we are getting error as **"Error loading block: invalid parameter(s): attributes".**

Please find the attached screenshot as a reference.
![image](https://github.com/wpify/custom-fields/assets/172026266/d1f1cb7d-f0f0-4e09-903b-9084e87c82fe)

Thanks in advance.

**Comment by mejta** [comment]
Hey, @flurdy-AB14, please check the new version of version 4.0. It has been completely rewritten but is backwards compatible. Those issues with blocks are gone now.
