### ISSUE TITLE
Component UI Issues

### ISSUE THREAD

**Issue by flurdy-AB14** [wpify/custom-fields#4]
Hi, there

We are using wpify/custom-fields at our end, recently we updated with the latest version, however we are seeing some inconsistencies with the UI. Example: Related to width, text going out of the component box with this latest version.

Please find the attached screenshots for your reference.

![image](https://github.com/wpify/custom-fields/assets/172026266/faa83f1c-a84b-4c8c-a398-be80eef16275)
![image (4)](https://github.com/wpify/custom-fields/assets/172026266/16f55399-83fa-47cb-89bb-f51079145bdf)
![image (3)](https://github.com/wpify/custom-fields/assets/172026266/68a27931-ffd7-4a8c-81f1-a39b3c415078)

Thanks in advance.

**Comment by Ashu23Queen** [comment]
u can use <div class="clearfix"></div> in custom html part where the ui is giving issue

**Comment by mejta** [comment]
@flurdy-AB14 @Ashu23Queen, please check the new version 4.0. It has been completely rewritten but is backwards compatible, so those issues should be gone.

Documentation (in progress) is here:
https://github.com/wpify/custom-fields/blob/master/docs/index.md

**Comment by mejta** [comment]
Closing
